### ISSUE TITLE
Unable to save Bypass Disk Space Check or download in folder. 

### ISSUE THREAD

**Issue by GlitchQueen** [NobilityDeviant/Wcofun.com_Downloader#17]
While working on downloading the movies, internet went down or computer went to sleep, and I came back to restart the download process, I just get "The download folder in your settings requires at least 150MB of free space.
Most videos average 
around 100MB.
If you are having issues with this, open the settings (CTRL + S) and 
enable Bypass Disk Space Check " even after enabling the setting and hitting save, popup shadow says Settings saved successfully, and closing the settings window, I get a confirmation prompt saying "You have unsaved changes. Would you like to save your settings?" Either way I answer it, I still am unable to download. I know its not the drive, its sitting at almost 7TBs free of space. I've also tried running it as administrator and gotten nothing. Its also not my anti-virus because i tried it with firewalls disabled for a minute to get the same results. Different drive works as well, but i dont want to have to move 555GB of movies from one drive to another just so i can resume the download.

**Comment by NobilityDeviant** [comment]
Yes i have seen an issue about the disk before. Let me look into it.

**Comment by NobilityDeviant** [comment]
Fixed the save issue in [2.0.1.1](https://github.com/NobilityDeviant/Wcofun.com_Downloader/releases/tag/2.0.1.1) and attempted to fix the space checking issue.
I have never experienced this issue myself, so i'm unable to replicate it.

Leaving the issue open until confirmed.

**Comment by GlitchQueen** [comment]
New update seemingly fixed the issue, will come back if it appears again, thanks!

**Comment by Shadpw2** [comment]
> New update seemingly fixed the issue, will come back if it appears again, thanks!

The issue persists in the current version.
![image](https://github.com/NobilityDeviant/Wcofun.com_Downloader/assets/30399377/dfed4279-f049-429e-a864-283a8a1d7778)

Failed to read episodes from https://www.wcofun.org/anime/regular-show
Error: ID is higher or equal to internal ID sequence: 
20 (vs. 1). Use ID 0 (zero) to insert new entities. 

![image](https://github.com/NobilityDeviant/Wcofun.com_Downloader/assets/30399377/c2ec42fe-35e7-4721-bb3a-df7816223f67)

Despite running the program successfully and ticking the Bypass check numerous times, after running the program once it resets all previous changes.
Temporary fix remains the same as changing the value of download threads and clicking the start button once again, successfully starts the download until completion.

Steps to reproduce:
Step one, launch program, with personalised settings
Step two, start a download from WCOFUN.ORG
Step three, once download is completed successfully, Use the Paste & start button with a new link.

Additional information:
The download location is set to S:/ while the location of the .jar is C:/
It also appears as tho the bypass checkbox is not saving in setting between program closure. As each time I restart the program the bypass checkbox is once again unticked.

**Comment by NobilityDeviant** [comment]
> > New update seemingly fixed the issue, will come back if it appears again, thanks!
> 
> The issue persists in the current version. ![image](https://user-images.githubusercontent.com/30399377/270160682-dfed4279-f049-429e-a864-283a8a1d7778.png)
> 
> Failed to read episodes from https://www.wcofun.org/anime/regular-show Error: ID is higher or equal to internal ID sequence: 20 (vs. 1). Use ID 0 (zero) to insert new entities.
> 
> ![image](https://user-images.githubusercontent.com/30399377/270160724-c2ec42fe-35e7-4721-bb3a-df7816223f67.png)
> 
> Despite running the program successfully and ticking the Bypass check numerous times, after running the program once it resets all previous changes. Temporary fix remains the same as changing the value of download threads and clicking the start button once again, successfully starts the download until completion.
> 
> Steps to reproduce: Step one, launch program, with personalised settings Step two, start a download from WCOFUN.ORG Step three, once download is completed successfully, Use the Paste & start button with a new link.
> 
> Additional information: The download location is set to S:/ while the location of the .jar is C:/ It also appears as tho the bypass checkbox is not saving in setting between program closure. As each time I restart the program the bypass checkbox is once again unticked.

Thank you for reporting that. This unrelated to the disk space and is an issue from ObjectBox. I have encountered this issue before, but I can't pinpoint exactly what causes it.
I believe it is when creating a new series in the database. I will look further into this.
For now, retry the download and it should continue without issues.
